#pragma once
#include <SDL.h>
#include "MiscFunctions.h"
#include "GraphicsHandler.h"
#include "TextHandler.h"
#include "TextBox.h"
#include "BorderedTextBox.h"
#include "ColoredBorderedTextBox.h"
#include "VerticalScrollTextBox.h"
#include "HorizontalScrollTextBox.h"
#include "ScrollTextBox.h"